### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by SeanTumulakNguyen** [Juwami/Weather-Wear#2]
## User Story
As a user, I want to purchase and pack new weather appropriate clothing for the duration of the trip I am going on. I want to input the location and time frame, and be able to see the weather forecast and recommended clothing

## Tasks
- [x] index.html has zip code location input
- [x] index.html has date picker input
- [x] index.html has gender preference input
- [x] index.html has area to display weather forecast based on input
- [x] index.html has area to display recommended clothing options based on input
- [x] index.html has area to display purchase options for clothing based on input

**Comment by noetinger** [comment]
- [x] Ball out
